/* autogenerated by Processing revision 1313 on 2026-03-30 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import bRigid.*;
import bRigid.util.*;
import bRigid.test.*;
import javax.vecmath.Vector3f;
import bRigid.*;
import javax.vecmath.Matrix4f;
import javax.vecmath.Vector3f;
import com.bulletphysics.linearmath.Transform;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class PhysicsCalculator extends PApplet {






BPhysics physics;

PImage logo = new PImage();

HUD hud = new HUD();

int fps = 60;

boolean showGrid = true;
boolean showOutlines = true;
boolean lights = false;

boolean pauseScreen = true;
boolean isPaused = true;
boolean settingsScreen = false;
boolean menuScreen = false;
boolean simulationScreen = false;
ArrayList<Force> forces = new ArrayList<>();
ArrayList<Object> objects = new ArrayList<>();
ArrayList<Button> pauseButtons = new ArrayList<>();
ArrayList<Button> simulationButtons = new ArrayList<>();
ArrayList<Button> settingsButtons = new ArrayList<>();
ArrayList<Button> menuButtons = new ArrayList<>();
ArrayList<Textbox> textboxes = new ArrayList<>();

ArrayList<Character> keysPressed = new ArrayList<>();

Dropdown addDropdown = new Dropdown(70, 15, 100, 40, "Add");

Object selectedObject = null;
Textbox selectedTextbox = null;
float previousScaleX = 1.0f;
float previousScaleY = 1.0f;
float previousScaleZ = 1.0f;
float previousRotX = 0.0f;
float previousRotY = 0.0f;
float previousRotZ = 0.0f;
//Slider timeStepSlider = new Slider(200, 10, 100, 40, 2.0f, 0.1f, 0.1f, 1.0f);

String previousScreen = "pause";

float camX, camY, camZ, camRotX, camRotY;

float simulationSpeed = 1.0f;
float timeStep = 0.01666f;

boolean mouseJustReleased = false;
boolean typing = false;

public void settings() {
  //size(640, 360, P3D);
  fullScreen(P3D);
  noSmooth();
  // pixelDensity(2);
}

public void setup() {
  background(100);
  frameRate(fps);

  physics = new BPhysics();
  physics.world.setGravity(new Vector3f(0, 9.81f * fps, 0));
  //surface.setResizable(true);
  logo = loadImage("Logo.png");
  textAlign(CENTER);
  textSize(12);
  noStroke();
  sphereDetail(18);
  pauseButtons.add(new Button(10, 350, 200, 40, "Run Simulation"));
  pauseButtons.add(new Button(10, 400, 200, 40, "Settings"));
  pauseButtons.add(new Button(10, 450, 200, 40, "Exit"));

  addDropdown.addOption("Dynamic Cube");
  addDropdown.addOption("Dynamic Sphere");
  addDropdown.addOption("Static Cube");
  addDropdown.addOption("Static Sphere");

  menuButtons.add(new Button(20, 70, 200, 40, "Settings"));
  menuButtons.add(new Button(20, 120, 200, 40, "Exit"));

  settingsButtons.add(new Button(10, 80, 220, 40, "Show Grid: ON"));
  settingsButtons.add(new Button(10, 130, 220, 40, "Show Outlines: ON"));
  settingsButtons.add(new Button(10, 180, 220, 40, "Lights: OFF"));
  settingsButtons.add(new Button(10, 230, 220, 40, "Back"));

  // objects.add(new StaticObject(0, 0, 0, 0, 0, 0, color(0, 255, 0), new Rectangle(1000, 0, 1000)));
  // objects.add(new DynamicObject(0, -200, 0, 0, 0, 0, color(255, 0, 0), new Rectangle(50, 50, 50), new BBox(this, 1, 15, 60, 15)));
  // objects.add(new DynamicObject(0, -100, 0, 0, 0, 0, color(255, 0, 0), new Sphere(25), new BSphere(this, 2, 0, 0, 0, 20)));

  objects.add(new StaticObject(0, 10, 0, 1000, 1, 1000, color(0, 255, 0)));
  objects.add(new DynamicObject(0, -100, 0, 50, 2, color(255, 0, 0)));
  objects.add(new DynamicObject(10, -200, 0, 50, 50, 50, 2, color(255, 0, 0)));

  camX = 0;
  camRotX = 0;
  camRotY = 0;

  camZ = -500;
  camY = -100;
}

public float[] eulerToQuaternion(float roll, float pitch, float yaw) {
  float cr = cos(roll * 0.5f);
  float sr = sin(roll * 0.5f);
  float cp = cos(pitch * 0.5f);
  float sp = sin(pitch * 0.5f);
  float cy = cos(yaw * 0.5f);
  float sy = sin(yaw * 0.5f);

  float w = cr * cp * cy - sr * sp * sy;
  float x = sr * cp * cy + cr * sp * sy;
  float y = cr * sp * cy + sr * cp * sy;
  float z = cr * cp * sy - sr * sp * cy;

  return new float[]{w, x, y, z};
}

public void draw() {
  if (settingsScreen) {
    hud.displaySettings(settingsButtons);
  } else if (pauseScreen) {
    hud.displayPauseScreen(pauseButtons);
  } else if (menuScreen) {
    displaySimulation(false, showGrid);
    hud.displayMenu(menuButtons);
  } else if (simulationScreen) {
    background(100);
    if (!isPaused && selectedObject == null) {
      physics.update();
    }
    displaySimulation(true, showGrid);
  }
  mouseJustReleased = false;
}

public void updateCamera() {
  if (keysPressed.contains('W')) {
    camX += 5 * sin(camRotY);
    camZ += 5 * cos(camRotY);
  }
  if (keysPressed.contains('S')) {
    camX -= 5 * sin(camRotY);
    camZ -= 5 * cos(camRotY);
  }
  if (keysPressed.contains('A')) {
    camX += 5 * cos(camRotY);
    camZ -= 5 * sin(camRotY);
  }
  if (keysPressed.contains('D')) {
    camX -= 5 * cos(camRotY);
    camZ += 5 * sin(camRotY);
  }

  if (keysPressed.contains(' ')) camY -= 5;
  if (keysPressed.contains('⇧')) camY += 5;

  if (keysPressed.contains('I')) camRotX += .05f;
  if (keysPressed.contains('K')) camRotX -= .05f;
  if (keysPressed.contains('J')) camRotY += .05f;
  if (keysPressed.contains('L')) camRotY -= .05f;

  if (camRotY > 2*PI) camRotY -= 2*PI;
  if (camRotY < 0) camRotY += 2*PI;
  if (camRotX >= PI/2) camRotX = PI/2 - 0.01f;
  if (camRotX <= -PI/2) camRotX = -PI/2 + 0.01f;

  //camera(camX, camY, camZ, camX + cos(camRotX) * sin(camRotY), camY + sin(camRotX), camZ + cos(camRotX) * cos(camRotY), 0, 1, 0);

  // for (Object o : objects) {
  //   if (o instanceof DynamicObject) {
  //     ((DynamicObject) o).update();
  //   }
  // }
}

public void displaySimulation(boolean updateHUD, boolean showGrid) {
  background(100);
  updateCamera();
  camera(camX, camY, camZ, camX + cos(camRotX) * sin(camRotY), camY + sin(camRotX), camZ + cos(camRotX) * cos(camRotY), 0, 1, 0);
  if (lights) {
    lights();
  }
  fill(150);

  for (Object o : objects) {
    o.display(showOutlines);
    // o.displayBRigid();
  }

  if (showGrid) {
    displayGrid();
  }

  if (updateHUD) {
    hud.displaySimulation(simulationButtons, addDropdown, isPaused);
  }

  if (selectedObject != null) {
    hud.displayObjectInfo();
  }
}

public void displayGrid() {
  stroke(200, 20);
  line(0, -3000, 0, 0, 3000, 0);

  float gridRadius = 3000;
  float step = 50;

  float startX = camX - gridRadius;
  startX -= startX % step;
  float endX = camX + gridRadius;
  endX -= endX % step;

  float startZ = camZ - gridRadius;
  startZ -= startZ % step;
  float endZ = camZ + gridRadius;
  endZ -= endZ % step;

  for (float x = startX; x <= endX; x += step) {
    stroke(200, map(abs(x - camX), 0, gridRadius, 20, -10));
    line(x, 0, startZ, x, 0, endZ);
  }

  for (float z = startZ; z <= endZ; z += step) {
    stroke(200, map(abs(z - camZ), 0, gridRadius, 20, -10));
    line(startX, 0, z, endX, 0, z);
  }
}

public boolean isMouseOver(Object o) {
  if (o.type.equals("Box")) {
    BBox b = (BBox) o.body;
    Vector3f pos = b.getPosition();
    float sx = screenX(pos.x, pos.y, pos.z);
    float sy = screenY(pos.x, pos.y, pos.z);

    float size = max(o.width, o.height);
    float edgeX = screenX(pos.x + size/2, pos.y, pos.z);
    float edgeY = screenY(pos.x + size/2, pos.y, pos.z);
    float sr = dist(sx, sy, edgeX, edgeY);

    if (dist(mouseX, mouseY, sx, sy) < sr) {
      return true;
    }
  } else if (o.type.equals("Sphere")) {
    BSphere s = (BSphere) o.body;
    Vector3f pos = s.getPosition();

    float sx = screenX(pos.x, pos.y, pos.z);
    float sy = screenY(pos.x, pos.y, pos.z);

    float edgeX = screenX(pos.x + o.radius, pos.y, pos.z);
    float edgeY = screenY(pos.x + o.radius, pos.y, pos.z);
    float sr = dist(sx, sy, edgeX, edgeY);

    if (dist(mouseX, mouseY, sx, sy) < sr) {
      return true;
    }
  }
  return false;
}

public void sortObjectsByDepth() {
  objects.sort((o1, o2) -> {
    float z1 = screenZ(o1.x, o1.y, o1.z);
    float z2 = screenZ(o2.x, o2.y, o2.z);
    return Float.compare(z2, z1);
  });
}

public void keyPressed() {
  char upperKey = Character.toUpperCase(key);
  if (!keysPressed.contains(upperKey)) {
    keysPressed.add(upperKey);
  }

  if (keyCode == ENTER) {
    if (typing) {
      selectedTextbox.enter();
    } else if (pauseScreen) {
      pauseScreen = false;
      simulationScreen = true;
      isPaused = false;
    }
  }
  if (keyCode == ESC) {
    key = 0;
    if (typing) {
      selectedTextbox.escape();
    } else if (selectedObject != null) {
      selectedObject = null;
      textboxes.clear();
    } else if (pauseScreen) {
      exit();
    } else if (simulationScreen) {
      simulationScreen = false;
      menuScreen = true;
      isPaused = true;
    } else if (menuScreen) {
      menuScreen = false;
      simulationScreen = true;
      isPaused = false;
    } else if (settingsScreen) {
      settingsScreen = false;
      if (previousScreen.equals("pause")) {
        pauseScreen = true;
      } else if (previousScreen.equals("menu")) {
        menuScreen = true;
      }
    }
  }

  if (keyCode == SHIFT) {
    keysPressed.add('⇧');
  }

  if (keyCode == BACKSPACE && typing) {
    if (selectedTextbox.label.length() > 0) {
      selectedTextbox.label = selectedTextbox.label.substring(0, selectedTextbox.label.length() - 1);
    }
  }
  if (typing) {
    if ((key >= '0' && key <= '9') || key == '.' || key == '-') {
      selectedTextbox.label += key;
    }
  } else {
    if ((key == 'P' || key == 'p') && simulationScreen) {
      isPaused = !isPaused;
    }
  }
}

public void keyReleased() {
  char upperKey = Character.toUpperCase(key);
  keysPressed.remove(Character.valueOf(upperKey));
  if (keyCode == SHIFT) {
    keysPressed.remove(Character.valueOf('⇧'));
  }
}

public void mousePressed() {
  if (mouseButton == LEFT) {
    if (!addDropdown.press()) {
      if (simulationScreen && selectedObject == null) {
        selectedObject = null;
        textboxes.clear();

        Object pick = null;
        float bestZ = Float.POSITIVE_INFINITY;
        for (Object o : objects) {
          if (isMouseOver(o)) {
            float z = screenZ(o.body.getPosition().x, o.body.getPosition().y, o.body.getPosition().z);
            if (pick == null || z < bestZ) {
              pick = o;
              bestZ = z;
            }
          }
        }

        if (pick != null) {
          selectedObject = pick;
          previousScaleX = 1.0f;
          previousScaleY = 1.0f;
          previousScaleZ = 1.0f;
          previousRotX = 0.0f;
          previousRotY = 0.0f;
          previousRotZ = 0.0f;
          textboxes.add(new Textbox(200, 90, 80, 30, String.format("%.1f", pick.body.getPosition().x)));
          textboxes.add(new Textbox(200, 130, 80, 30, String.format("%.1f", pick.body.getPosition().y)));
          textboxes.add(new Textbox(200, 170, 80, 30, String.format("%.1f", pick.body.getPosition().z)));
          textboxes.add(new Textbox(200, 50, 80, 30, String.format("%.1f", pick.body.getMass())));
          textboxes.add(new Textbox(200, 210, 80, 30, "1.0"));
          textboxes.add(new Textbox(200, 250, 80, 30, "1.0"));
          textboxes.add(new Textbox(200, 290, 80, 30, "1.0"));
          textboxes.add(new Textbox(200, 330, 80, 30, "0.0"));
          textboxes.add(new Textbox(200, 370, 80, 30, "0.0"));
          textboxes.add(new Textbox(200, 410, 80, 30, "0.0"));
        }
      }
    }
  }
}

public void mouseReleased() {
  mouseJustReleased = true;
}

public void mouseDragged() {
  if (simulationScreen && mouseButton == RIGHT) {
    camRotY += (pmouseX - mouseX) * 0.005f;
    camRotX += (pmouseY - mouseY) * -0.005f;
  }
}
public class Button {
    int x, y, w, h;
    String label;
    boolean hovered = false;

    Button(int x, int y, int w, int h, String label) {
        this.x = x;
        this.y = y;
        this.w = w;
        this.h = h;
        this.label = label;
    }

    public void display() {
        stroke(0);
        fill(hovered ? 150 : 200);
        rect(x, y, w, h);
        fill(0);
        textAlign(CENTER, CENTER);
        text(label, x + w / 2, y + h / 2);
        noStroke();
    }

    public void update() {
        hovered = mouseX > x && mouseX < x + w && mouseY > y && mouseY < y + h;
    }

    public boolean isClicked() {
        return hovered && mouseJustReleased;
    }
}
class Dropdown {
    float x, y, w, h;
    String label;
    ArrayList<Button> options;
    boolean isOpen = false;

    Dropdown(float x, float y, float w, float h, String label) {
        this.x = x;
        this.y = y;
        this.w = w;
        this.h = h;
        this.label = label;
        options = new ArrayList<Button>();
    }

    public void addOption(String optionLabel) {
        options.add(new Button((int)x, (int)(y + h * (options.size() + 1)), (int)w, (int)h, optionLabel));
    }

    public void display() {
        fill(200);
        stroke(0);
        rect(x, y, w, h);
        fill(0);
        triangle(x+w-15, y+h/2-2, x+w-10, y+h/2+5, x+w-5, y+h/2-2);
        textAlign(CENTER, CENTER);
        text(label, x + w / 2, y + h / 2);

        if (isOpen) {
            for (Button option : options) {
                option.display();
            }
        }
        noStroke();
    }

    public void update() {
        // if (mouseX > x && mouseX < x + w && mouseY > y && mouseY < y + h) {
        //     if (mousePressed) {
        //         isOpen = !isOpen;
        //     }
        // }

        if (isOpen) {
            for (Button option : options) {
                option.update();
            }
        }
    }

    public boolean press() {
        if (mouseX > x && mouseX < x + w && mouseY > y && mouseY < y + h) {
            isOpen = !isOpen;
            return true;
        }
        return false;
    }
}
public class DynamicObject extends Object {

  DynamicObject(float x, float y, float z, float width, float height, float depth, float mass, int col) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.width = width;
    this.height = height;
    this.depth = depth;
    this.mass = mass;
    this.type = "Box";
    this.col = col;
    body = new BBox(PhysicsCalculator.this, mass, width, height, depth);
    body.setPosition(x, y, z);
    physics.addBody(body);
  }

  DynamicObject(float x, float y, float z, float radius, float mass, int col) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.radius = radius;
    this.mass = mass;
    this.type = "Sphere";
    this.col = col;
    body = new BSphere(PhysicsCalculator.this, mass, x, y, z, radius);
    physics.addBody(body);
  }

  // DynamicObject(color col, BObject body) {
  //   this.col = col;
  //   this.body = body;
  //   physics.addBody(body);
  // }

  // public void update() {
  //   forces.clear();

  //   forces.add(new NaturalForce("Gravity", 0, mass * 9.81f, 0, 0, 0, 0));

  //   for (Force f : forces) {
  //     f.applyForce(this);
  //   }

  //   float step = 0.1;

  //   for (float i = 0; i < abs(velocityX); i += step) {
  //     x += step * abs(velocityX)/velocityX;
  //     if (velocityX != 0) {
  //       for (Object o : objects) {
  //         if (o != this && collidesWith(o)) {
  //           forces.add(new NaturalForce("Normal", -velocityX * mass, 0, 0, 0, 0, 0));
  //           for (Force f : forces) {
  //             f.applyForce(this);
  //           }
  //           x -= step * abs(velocityX)/velocityX;
  //           break;
  //         }
  //       }
  //     }
  //   }

  //   for (float i = 0; i < abs(velocityY); i += step) {
  //     y += step * abs(velocityY)/velocityY;
  //     if (velocityY != 0) {
  //       for (Object o : objects) {
  //         if (o != this && collidesWith(o)) {
  //           forces.add(new NaturalForce("Normal", 0, -velocityY * mass, 0, 0, 0, 0));
  //           for (Force f : forces) {
  //             f.applyForce(this);
  //           }
  //           y -= step * abs(velocityY)/velocityY;
  //           break;
  //         }
  //       }
  //     }
  //   }

  //   for (float i = 0; i < abs(velocityZ); i += step) {
  //     z += step * abs(velocityZ)/velocityZ;
  //     if (velocityZ != 0) {
  //       for (Object o : objects) {
  //         if (o != this && collidesWith(o)) {
  //           forces.add(new NaturalForce("Normal", 0, 0, -velocityZ * mass, 0, 0, 0));
  //           for (Force f : forces) {
  //             f.applyForce(this);
  //           }
  //           z -= step * abs(velocityZ)/velocityZ;
  //           break;
  //         }
  //       }
  //     }
  //   }
  // }
}
public abstract class Force {
    float x, y, z, torqueX, torqueY, torqueZ;

    // public void applyForce(DynamicObject o) {
    //     o.velocityX += x/o.mass * timeStep;
    //     o.velocityY += y/o.mass * timeStep;
    //     o.velocityZ += z/o.mass * timeStep;
    //     o.omegaX += torqueX * timeStep;
    //     o.omegaY += torqueY * timeStep;
    //     o.omegaZ += torqueZ * timeStep;
    // }

    // PVector getForceVector() {
    //     return new PVector(x, y, z);
    // }

    // PVector getTorqueVector() {
    //     return new PVector(torqueX, torqueY, torqueZ);
    // }
}
public class HUD {
  public void displaySimulation(ArrayList<Button> simulationButtons, Dropdown addDropdown, boolean isPaused) {
    pushMatrix();
    camera();
    noLights();
    hint(PApplet.DISABLE_DEPTH_TEST);

    if (isPaused) {
      fill(0);
      triangle(width - 40, 20, width - 40, 40, width - 20, 30);
    } else {
      fill(0);
      rect(width - 40, 20, 5, 20);
      rect(width - 25, 20, 5, 20);
    }

    for (Button b : simulationButtons) {
      b.update();
      b.display();
      if (b.isClicked() && b.label.equals("Add")) {
        
      }
    }

    addDropdown.update();
    addDropdown.display();

    for (Button b : addDropdown.options) {
      if (b.isClicked()) {
        String option = b.label;
        if (option.equals("Dynamic Cube")) {
          objects.add(new DynamicObject(0, -100, 0, 50, 50, 50, 1, color(255, 0, 0)));
        } else if (option.equals("Dynamic Sphere")) {
          objects.add(new DynamicObject(0, -100, 0, 50, 1, color(255, 0, 0)));
        } else if (option.equals("Static Cube")) {
          objects.add(new StaticObject(0, -100, 0, 50, 50, 50, color(0, 255, 0)));
        } else if (option.equals("Static Sphere")) {
          objects.add(new StaticObject(0, -100, 0, 50, color(0, 255, 0)));
        }
      }
    }

    hint(PApplet.ENABLE_DEPTH_TEST);
    popMatrix();
  }

  public void displayPauseScreen(ArrayList<Button> pauseButtons) {
    pushMatrix();
    camera();
    hint(PApplet.DISABLE_DEPTH_TEST);

    background(100);
    fill(255);
    logo = loadImage("Logo.png");
    logo.resize(width, height);
    image(logo, 0, 0);
    for (Button b : pauseButtons) {
      b.update();
      b.display();
      if (b.isClicked() && b.label.equals("Run Simulation")) {
        pauseScreen = false;
        simulationScreen = true;
        isPaused = true;
      } else if (b.isClicked() && b.label.equals("Settings")) {
        previousScreen = "pause";
        settingsScreen = true;
        pauseScreen = false;
      } else if (b.isClicked() && b.label.equals("Exit")) {
        exit();
      }
    }
    hint(PApplet.ENABLE_DEPTH_TEST);
    popMatrix();
  }

  public void displayMenu(ArrayList<Button> menuButtons) {
    pushMatrix();
    camera();
    hint(PApplet.DISABLE_DEPTH_TEST);

    fill(125);
    rect(10, 10, 300, 200);

    fill(0);
    textSize(20);
    text("Paused", 50, 25);
    textSize(12);

    for (Button b : menuButtons) {
      b.update();
      b.display();
      if (b.isClicked() && b.label.equals("Settings")) {
        previousScreen = "menu";
        settingsScreen = true;
        menuScreen = false;
      }
      if (b.isClicked() && b.label.equals("Exit")) {
        menuScreen = false;
        pauseScreen = true;
      }
    }
    hint(PApplet.ENABLE_DEPTH_TEST);
    popMatrix();
  }

  public void displaySettings(ArrayList<Button> settingsButtons) {
    pushMatrix();
    camera();
    hint(PApplet.DISABLE_DEPTH_TEST);

    background(100);

    fill(0);
    textSize(20);
    text("Settings", 50, 25);
    textSize(12);
    // timeStepSlider.update();
    // timeStepSlider.display();
    for (Button b : settingsButtons) {
      if (b.label.startsWith("Show Grid")) {
        b.label = "Show Grid: " + (showGrid ? "ON" : "OFF");
      } else if (b.label.startsWith("Show Outlines")) {
        b.label = "Show Outlines: " + (showOutlines ? "ON" : "OFF");
      } else if (b.label.startsWith("Lights")) {
        b.label = "Lights: " + (lights ? "ON" : "OFF");
      }

      b.update();
      b.display();

      if (b.isClicked()) {
        if (b.label.startsWith("Show Grid")) {
          showGrid = !showGrid;
          b.label = "Show Grid: " + (showGrid ? "ON" : "OFF");
        } else if (b.label.startsWith("Show Outlines")) {
          showOutlines = !showOutlines;
          b.label = "Show Outlines: " + (showOutlines ? "ON" : "OFF");
        } else if (b.label.startsWith("Lights")) {
          lights = !lights;
          b.label = "Lights: " + (lights ? "ON" : "OFF");
        } else if (b.label.equals("Back")) {
          settingsScreen = false;
          if (previousScreen.equals("pause")) {
            pauseScreen = true;
          } else if (previousScreen.equals("menu")) {
            menuScreen = true;
          }
        }
      }
    }
    hint(PApplet.ENABLE_DEPTH_TEST);
    popMatrix();
  }

  public void displayObjectInfo() {
    pushMatrix();
    camera();
    hint(PApplet.DISABLE_DEPTH_TEST);

    fill(125);
    noStroke();
    textSize(20);
    rect(10, 10, 320, 450);
    fill(0);
    text("Object Info", 65, 25);
    textSize(12);
    text("Mass:", 50, 50);
    text("X:", 50, 90);
    text("Y:", 50, 130);
    text("Z:", 50, 170);
    text("ScaleX:", 50, 210);
    text("ScaleY:", 50, 250);
    text("ScaleZ:", 50, 290);
    text("RotX:", 50, 330);
    text("RotY:", 50, 370);
    text("RotZ:", 50, 410);
    for (Textbox t : textboxes) {
      t.update();
      t.display();
    }

    if (selectedObject != null && textboxes.size() >= 10) {
      float nx = textboxes.get(0).value;
      float ny = textboxes.get(1).value;
      float nz = textboxes.get(2).value;
      float nm = textboxes.get(3).value;
      float nsx = textboxes.get(4).value;
      float nsy = textboxes.get(5).value;
      float nsz = textboxes.get(6).value;
      float nrx = textboxes.get(7).value;
      float nry = textboxes.get(8).value;
      float nrz = textboxes.get(9).value;

      if (selectedObject.body.getPosition().x != nx || selectedObject.body.getPosition().y != ny || selectedObject.body.getPosition().z != nz) {
        selectedObject.body.setPosition(nx, ny, nz);
        selectedObject.x = nx;
        selectedObject.y = ny;
        selectedObject.z = nz;
      }
      if (selectedObject.body.getMass() != nm) {
        selectedObject.body.setMass(nm);
        selectedObject.mass = nm;
      }
      if (selectedObject.type.equals("Box")) {
        if (nsx != previousScaleX) {
          selectedObject.width *= nsx / previousScaleX;
          previousScaleX = nsx;
        }
        if (nsy != previousScaleY) {
          selectedObject.height *= nsy / previousScaleY;
          previousScaleY = nsy;
        }
        if (nsz != previousScaleZ) {
          selectedObject.depth *= nsz / previousScaleZ;
          previousScaleZ = nsz;
        }
      } else if (selectedObject.type.equals("Sphere")) {
        if (nsx != previousScaleX) {
          selectedObject.radius *= nsx / previousScaleX;
          previousScaleX = nsx;
        }
      }

      if (nrx != previousRotX || nry != previousRotY || nrz != previousRotZ) {
        float[] q = eulerToQuaternion(nrx * PI / 180, nry * PI / 180, nrz * PI / 180);
        float qw = q[0];
        float qx = q[1];
        float qy = q[2];
        float qz = q[3];
        float angle = 2 * acos(qw);
        float s = sqrt(1 - qw * qw);
        Vector3f axis;
        if (s < 0.0001f) {
          axis = new Vector3f(1, 0, 0);
        } else {
          axis = new Vector3f(qx / s, qy / s, qz / s);
        }
        selectedObject.body.setRotation(axis, angle);
        previousRotX = nrx;
        previousRotY = nry;
        previousRotZ = nrz;
      }
    }

    hint(PApplet.ENABLE_DEPTH_TEST);
    popMatrix();
  }
}
public class NaturalForce extends Force {

    String type;
    
    NaturalForce(String type, float x, float y, float z, float torqueX, float torqueY, float torqueZ) {
        this.type = type;
        this.x = x;
        this.y = y;
        this.z = z;
        this.torqueX = torqueX;
        this.torqueY = torqueY;
        this.torqueZ = torqueZ;
    }
}





public abstract class Object {
  float x, y, z, mass, radius, width, height, depth;

  String type;

  int col;

  BObject body;

  public void display(boolean showOutlines) {

    Transform trans = body.rigidBody.getWorldTransform(new Transform());
    Matrix4f mat = new Matrix4f();
    trans.getMatrix(mat);

    if (type.equals("Box")) {
      BBox b = (BBox) body;
      pushMatrix();
      translate(b.getPosition().x, b.getPosition().y, b.getPosition().z);
      applyMatrix(
        mat.m00, mat.m01, mat.m02, 0,
        mat.m10, mat.m11, mat.m12, 0,
        mat.m20, mat.m21, mat.m22, 0,
        0, 0, 0, 1
        );
      fill(col);
      if (showOutlines) {
        stroke(0);
      } else {
        noStroke();
      }
      box(width, height, depth);
      popMatrix();
      noStroke();
    } else if (type.equals("Sphere")) {
      BSphere s = (BSphere) body;
      pushMatrix();
      translate(s.getPosition().x, s.getPosition().y, s.getPosition().z);
      applyMatrix(
        mat.m00, mat.m01, mat.m02, 0,
        mat.m10, mat.m11, mat.m12, 0,
        mat.m20, mat.m21, mat.m22, 0,
        0, 0, 0, 1
        );
      fill(col);
      if (showOutlines) {
        stroke(0);
      } else {
        noStroke();
      }
      sphere(radius);
      popMatrix();
      noStroke();
    }

    if (this instanceof DynamicObject) {
      x = body.getPosition().x;
      y = body.getPosition().y;
      z = body.getPosition().z;
    }
  }

  public void displayBRigid() {
    body.display();
  }
}
class Slider {
    float x, y, width, height;
    float minValue, maxValue, step;
    float currentValue;
    boolean isDragging = false;

    Slider(float x, float y, float width, float height, float minValue, float maxValue, float step, float initialValue) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.step = step;
        this.currentValue = initialValue;
    }

    public void display() {
        fill(200);
        rect(x, y, width, height);
        fill(100);
        ellipse(map(currentValue, minValue, maxValue, x, x + width), y + height / 2, height, height);
    }

    public void update() {
        if (isDragging && mouseX >= x && mouseX <= x + width && mouseY >= y && mouseY <= y + height) {
            float mouseValue = map(mouseX, x, x + width, minValue, maxValue);
            currentValue = round(mouseValue / step) * step;
            currentValue = constrain(currentValue, minValue, maxValue);
            isDragging = true;
        } else if (mouseJustReleased) {
            isDragging = false;
        }
    }
}
public class StaticObject extends Object {
  StaticObject(float x, float y, float z, float width, float height, float depth, int col) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.width = width;
    this.height = height;
    this.depth = depth;
    mass = 0;
    this.type = "Box";
    this.col = col;
    body = new BBox(PhysicsCalculator.this, 0, width, height, depth);
    body.setPosition(x, y, z);
    physics.addBody(body);
  }

  StaticObject(float x, float y, float z, float radius, int col) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.radius = radius;
    mass = 0;
    this.type = "Sphere";
    this.col = col;
    body = new BSphere(PhysicsCalculator.this, 0, x, y, z, radius);
    physics.addBody(body);
  }
}
public class Textbox extends Button {

    Button leftButton, rightButton;

    boolean selected;

    float value;

    String tempLabel;

    Textbox(int x, int y, int w, int h, String label) {
        super(x, y, w, h, label);
        leftButton = new Button(x - 30, y, 30, h, "-");
        rightButton = new Button(x + w, y, 30, h, "+");
        selected = false;

        value = Float.parseFloat(label);
        tempLabel = label;
    }

    @Override public 
    void display() {
        super.display();
        leftButton.display();
        rightButton.display();
    }

    @Override public 
    void update() {
        super.update();
        leftButton.update();
        rightButton.update();
        if (isClicked()) {
            selected = true;
            tempLabel = label;
            label = "";
            typing = true;
            selectedTextbox = this;
        }

        if (leftButton.isClicked()) {
            value -= 10.0f;
            label = String.format("%.1f", value);
        }
        if (rightButton.isClicked()) {
            value += 10.0f;
            label = String.format("%.1f", value);
        }

    }

    public void escape() {
        selected = false;
        typing = false;
        selectedTextbox = null;
        label = tempLabel;
    }

    public void enter() {
        try {
            value = Float.parseFloat(label);
            label = String.format("%.1f", value);
        } catch (NumberFormatException e) {
            label = tempLabel;
        }
        selected = false;
        typing = false;
        selectedTextbox = null;
    }
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--hide-stop", "PhysicsCalculator" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
